### ISSUE TITLE
Make the mapmaker a full-fledged map editor with fully-featured progress tracking.

### ISSUE THREAD

**Issue by ClobberXD** [MT-CTF/capturetheflag#221]
In case of changes being requested, schems created by `ctf_map`'s map maker mode has to be edited manually, and manually modifying values like `team.1.pos` and `team.2.pos` is outright impossible.

It would be great to be able to load existing schems and their conf files, and modify them through `ctf_map` itself. This would especially be useful for modifications to flag positions.

Features planned:
- [ ] Undo barrier placement when resetting context.
- [ ] Track map-making progress, and show only the actions relevant to the current phase.
  - e.g. Once barriers are placed, they can't be placed again without resetting context.
- [ ] Make context work with only one schem at a time.
  - This prevents messing up the map maker when multiple maps are being created simultaneously. e.g. pos1 and pos2, barrier placement, emerge area, all depend on the critical assumption that the player is working on the same map. If the player starts working on a different map before finishing the current map, then they'd have to manually enter the coords of the first map for place barriers, emerge area, etc. to correctly work.
  - If a player wants to ditch the current map, they'll have to reset the context first (deleting flags and barriers in the process), and only then start working on the next.
- [ ] Load existing schem into context from provided file-path, and save back to file.
- [ ] Create/Edit flag positions and chest-zones.

**Comment by ClobberXD** [comment]
Updated first post with a clear road-map for improving the map maker

**Comment by rubenwardy** [comment]
Craft The Web's map editor has support for creating worlds to edit the map in. It does this by creating a new world directory, symlinking the world mod (ctf_map* equivalent), and copying the schematic across

https://github.com/CERN/CTW/blob/develop/build/create_worldbuilder.sh

https://github.com/CERN/CTW/blob/develop/mods/world/builder.lua#L10

**Comment by ClobberXD** [comment]
That's an interesting (and safer?) approach, thanks for the references! But the map maker would have to exit the current world and enter a new world. Also, manually creating a world has a disadvantage (albeit a far-fetched one) wherein if MT changes the world dir structure, even in the smallest relevant way, this code would be broken.

I'd prefer to avoid the suggested approach for the aforementioned reasons, but I'll see if there's anything that can come in handy. I'm thinking placing the schem high up (at around y=20000), after checking there's only air in the selected region. The player would be teleported to the region once the schem has been placed.

**Comment by rubenwardy** [comment]
> MT changes the world dir structure, even in the smallest relevant way

This would be a major breaking change
